### ISSUE TITLE
bug: hscan arg should be inited in DoInit

### ISSUE THREAD

**Issue by AlexStocks** [OpenAtomFoundation/pikiwidb-raft#149]
### Is this a regression?

Yes

### Description

<img width="986" alt="image" src="https://github.com/OpenAtomFoundation/pikiwidb/assets/7959374/af24245a-2222-42e3-ab01-c73ee6e52b4f">

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by AlexStocks** [comment]
等着 QX 的网络库 PR 合并

**Comment by LuckyTom1024** [comment]
@lqxhub
