### ISSUE TITLE
feat:Stroage floyd

### ISSUE THREAD

**Issue by dingxiaoshuai123** [OpenAtomFoundation/pikiwidb-raft#153]
### Description

TODO：
1、多 key 命令的一致性处理，例如 MGet、SInter 。P0
2、重复 Key 问题。 P1
3、优化 InternalKey 的初始化。p2
4、增加 Storage 的测试 p2
5、使用 spdlog 替换 glog  done
6、增加配置文件, 减小 max_total_wal_size.

### Proposed solution

none

### Alternatives considered

none

**Comment by super-Pan66** [comment]
周会记录： TODO 2 https://github.com/OpenAtomFoundation/pikiwidb/pull/240
 TODO 5 done
