### ISSUE TITLE
bug: floyd atomic operation problem under multi-key command

### ISSUE THREAD

**Issue by Mixficsol** [OpenAtomFoundation/pikiwidb-raft#154]
### Description

`Floyd` 采用多 `RocksDB` 实例，每个 `Key` 可能 `Hash` 到不同的 `RocksDB` 实例，与 `BlackWidow` 不同的是 `Floyd` 下的 `Key` 不再以数据类型去区分 `RocksDB`, 即一个 `RocksDB` 下可能会存在不同类型的 `Key`，那么对于 `Redis` 命令中如：`SInter` 这种操作多个 `Key` 的情况下，需要重新设计下确保操作的一致性，对 `BlackWidow` 来说对于 `Sinter` 这种命令，由于所有的 `Set` 类型都在同一个 `RocksDB` 下，所以对于 `SInter` 这种读命令不需要进行上 `key` 锁，只需要在相应的 `RocksDB` 打一个快照然后进行操作即可，但是在 `Floyd` 下，多个 `Key` 可能存在多个 `RocksDB` 下，对于这种问题我们需要一种解决方式。

**Comment by 578223592** [comment]
想问下这个问题是如何解决的？ @Mixficsol
