### ISSUE TITLE
feat: flushdb & flushall cmd 

### ISSUE THREAD

**Issue by dingxiaoshuai123** [OpenAtomFoundation/pikiwidb-raft#182]
### Is this a regression?

Yes

### Description

Reimplement the flushdb and flushall commands.

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by LuckyTom1024** [comment]
https://github.com/OpenAtomFoundation/pikiwidb/pull/205
