### ISSUE TITLE
feat: Adjust the UnboundedBuffer::PushData() function to C++ style.

### ISSUE THREAD

**Issue by KKorpse** [OpenAtomFoundation/pikiwidb-raft#234]
### Description

这个接口有点太过于原始了，用起来很别扭，字符数量是靠人来数的：
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/40883262/e6d77fba-c03b-4710-b716-8f5d952611f1)

### Proposed solution

其实可以简单封装一下，提供一个这样的接口，使用起来合理一点。
```cpp
std::size_t UnboundedBuffer::PushData(const std::string_view& data) {
  return PushData(data.data(), data.size());
}
```
新接口使用方式：
```cpp
  UnboundedBuffer req;
  req.PushData("RAFT.NODE ADD ");
```

### Alternatives considered

现在总共需要修改的地方也不多，总共 36 处左右，可以考虑换一下？
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/40883262/ff1663e7-02d2-46a3-95bf-bf59fa102805)

**Comment by hnwyllmm** [comment]
给我试一下？

**Comment by KKorpse** [comment]
> 给我试一下？

ok

**Comment by hnwyllmm** [comment]
string_view 是C++17才支持的，但是pikiwidb希望使用的是C++11。
替代方案是实现 const char *版本的函数，但是使用const char *版本会降低性能。
有什么建议吗？

**Comment by KKorpse** [comment]
> string_view 是C++17才支持的，但是pikiwidb希望使用的是C++11。 替代方案是实现 const char *版本的函数，但是使用const char *版本会降低性能。 有什么建议吗？

README 有点过时了，正在重新写。
其实最高用到 C++ 20 都行，不一定限制在 11。

 Cmake 文件有这么一行
```cmake
SET(CMAKE_CXX_STANDARD 20)
```
