### ISSUE TITLE
The SET command overwrites other types of key data with the same name

### ISSUE THREAD

**Issue by lqxhub** [OpenAtomFoundation/pikiwidb-raft#241]
In redis the `SET` common is 'top-level', can overwrite data of other types of keys with the same name.

example:

```shell
redis> HSET key field 1
(integer) 1
redis> type key
hash
redis> set key abc
OK
redis> type key
string
```
redis SET command doc: https://redis.io/commands/set/

**Comment by super-Pan66** [comment]
会议标记： 等待https://github.com/OpenAtomFoundation/pikiwidb/pull/240合并再考虑
