### ISSUE TITLE
About the license issue in cmake utils

### ISSUE THREAD

**Issue by PragmaTwice** [OpenAtomFoundation/pikiwidb-raft#250]
### Describe the problem that you experienced

Hi pikiwidb maintainers,

I noticed that the `cmake/utils.cmake` [1] file has been directly copied from Apache Kvrocks [2] (BTW it's written by me). 
However, the license header states that it is copyrighted by Qihoo, Inc. and licensed under the BSD license. 
This **contradicts** the Apache-2.0 license of Apache Kvrocks.

Apache Kvrocks is a project licensed under Apache-2.0 and owned by ASF. 
If you wish to use code from Apache Kvrocks, please ensure to include the ASF license header correctly. 
Changing the license or copyright owner without permission from ASF is not permitted.

[1] https://github.com/OpenAtomFoundation/pikiwidb/blob/b7f075eb2381f72b40d9a15ed9ee7bf7e34644e9/cmake/utils.cmake
[2] https://github.com/apache/kvrocks/blob/bb665f6fc2de7cb1215240866d48e92adfed43b1/cmake/utils.cmake

Best,
Twice

cc @tedli

**Comment by dingxiaoshuai123** [comment]
> ### Describe the problem that you experienced
> Hi pikiwidb maintainers,
> 
> I noticed that the `cmake/utils.cmake` [1] file has been directly copied from Apache Kvrocks [2] (BTW it's written by me). However, the license header states that it is copyrighted by Qihoo, Inc. and licensed under the BSD license. This **contradicts** the Apache-2.0 license of Apache Kvrocks.
> 
> Apache Kvrocks is a project licensed under Apache-2.0 and owned by ASF. If you wish to use code from Apache Kvrocks, please ensure to include the ASF license header correctly. Changing the license or copyright owner without permission from ASF is not permitted.
> 
> [1] https://github.com/OpenAtomFoundation/pikiwidb/blob/b7f075eb2381f72b40d9a15ed9ee7bf7e34644e9/cmake/utils.cmake [2] https://github.com/apache/kvrocks/blob/bb665f6fc2de7cb1215240866d48e92adfed43b1/cmake/utils.cmake
> 
> Best, Twice
> 
> cc @tedli
> 
> ### Enter the URL of the topic with the problem
> _No response_
> 
> ### Describe what you were looking for in the documentation
> _No response_
> 
> ### Describe the actions that led you to experience the problem
> _No response_
> 
> ### Describe what you want to experience that would fix the problem
> _No response_
> 
> ### Add a screenshot if that helps illustrate the problem
> _No response_
> 
> ### If this problem caused an exception or error, please paste it here
> _No response_
> 
> ### If the problem is browser-specific, please specify the device, OS, browser, and version
> _No response_
> 
> ### Provide any additional information here in as much as detail as you can
> _No response_

As this file is imported from PR https://github.com/OpenAtomFoundation/pikiwidb/pull/20 which is useless now. We have delete it in https://github.com/OpenAtomFoundation/pikiwidb/pull/261. Thanks for your reminder.  

We really appreciate your contribution to our project. Any issue/pr is welcome from you.
