### ISSUE TITLE
bug: do not config worker-threads and slave-threads, program will abnormal quit

### ISSUE THREAD

**Issue by hahahashen** [OpenAtomFoundation/pikiwidb-raft#286]
### Is this a regression?

Yes

### Description

当前有配置文件运行项目时，如果配置文件中没有指定worker-threads以及slave-threads，那么LoadPikiwiDBConfig函数的语句
cfg.worker_threads_num = parser.GetData<int>("worker-threads", 1);  cfg.slave_threads_num = parser.GetData<int>("slave-threads", 1);就会设置.worker_threads_num、slave_threads_num 变量为1，而在IOThreadPool::SetWorkerNum函数处就会直接返回，导致IOThreadPool的成员变量worker_num_为初始值0，导致void WorkIOThreadPool::PushWriteTask(std::shared_ptr<PClient> client) 函数中出现除0错误，auto pos = ++counter_ % worker_num_;使得程序异常退出

解决方案：
方案1：设置默认值处，默认值设置为2
方案2：考虑IOThreadPool::SetWorkerNum函数if (num <= 1) 改为if (num <1)

### Screenshots or videos

![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/59725322/9e6dbd57-1883-4d3f-ae1e-37c797e86a09)
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/59725322/18fa732e-5200-4f2c-800a-dc196ce989b3)
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/59725322/af5c6f35-e52b-4e65-814b-54a228e4ad67)
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/59725322/3c140d58-1564-4340-be3f-363ff1f56abc)

### Please provide the version you discovered this bug in (check about page for version information)

```true
commit hash：57248c3b612a5c2bf0a89586262b616eff1ffde4
```

**Comment by AlexStocks** [comment]
这个 issue title 怎么是空的

**Comment by hahahashen** [comment]
> 这个 issue title 怎么是空的
刚刚编辑上了= =

**Comment by hahahashen** [comment]
或者运行的时候conf指定worker-threads以及slave-threads为1时也会导致运行时程序异常退出
