### ISSUE TITLE
bug: exit pikiwidb with error

### ISSUE THREAD

**Issue by dingxiaoshuai123** [OpenAtomFoundation/pikiwidb-raft#293]
### Is this a regression?

Yes

### Description

使用 ctrl + c 退出后, 会有错误.
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/56024577/c73266e2-5329-450b-8d96-9a6ceb6bc336)

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by AlexStocks** [comment]
@Tangruilin

**Comment by Tangruilin** [comment]
feat: transform kv and hash command using blackwidow without cache (#101)

**Comment by Tangruilin** [comment]
> feat: transform kv and hash command using blackwidow without cache (#101)

确认了是这个 patch 引入的

**Comment by Tangruilin** [comment]
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/23651891/1466cf83-75f2-4919-8480-8b63e94f134c)
我逐个修改文件确认了一下
失败是因为从 leveldb 切换到了 rocksdb，这里吧 dump 文件的逻辑去掉了

目前怀疑是退出的时候 rockdb 没有正常关闭，然后 pikidb 里面开了多个 rocksdb  示例，rocksdb 在退出的时候失败了

**Comment by Tangruilin** [comment]
> ![image](https://private-user-images.githubusercontent.com/23651891/330729367-1466cf83-75f2-4919-8480-8b63e94f134c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjMxMzUsIm5iZiI6MTcxNTc2MjgzNSwicGF0aCI6Ii8yMzY1MTg5MS8zMzA3MjkzNjctMTQ2NmNmODMtNzVmMi00OTE5LTg0ODAtOGI2M2U5NGYxMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA4NDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NGIxNjkwZTBkODg5Mzg5YTRlMTU3OGI5N2IyOGQwODI1YTViODkzNzU5YzA5MDVjYWUyMDU1NjFmYzRiMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sTf3Rqx_AHAsNkqISC1jzandnhhbsjckGIQDU4SUJFg) 我逐个修改文件确认了一下 失败是因为从 leveldb 切换到了 rocksdb，这里吧 dump 文件的逻辑去掉了
> 
> 目前怀疑是退出的时候 rockdb 没有正常关闭，然后 pikidb 里面开了多个 rocksdb 示例，rocksdb 在退出的时候失败了


store.h
store.cc

引入bug 的是这两个文件

**Comment by Tangruilin** [comment]
> > ![image](https://private-user-images.githubusercontent.com/23651891/330729367-1466cf83-75f2-4919-8480-8b63e94f134c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjMxMzUsIm5iZiI6MTcxNTc2MjgzNSwicGF0aCI6Ii8yMzY1MTg5MS8zMzA3MjkzNjctMTQ2NmNmODMtNzVmMi00OTE5LTg0ODAtOGI2M2U5NGYxMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA4NDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NGIxNjkwZTBkODg5Mzg5YTRlMTU3OGI5N2IyOGQwODI1YTViODkzNzU5YzA5MDVjYWUyMDU1NjFmYzRiMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sTf3Rqx_AHAsNkqISC1jzandnhhbsjckGIQDU4SUJFg) 我逐个修改文件确认了一下 失败是因为从 leveldb 切换到了 rocksdb，这里吧 dump 文件的逻辑去掉了
> > 目前怀疑是退出的时候 rockdb 没有正常关闭，然后 pikidb 里面开了多个 rocksdb 示例，rocksdb 在退出的时候失败了
> 
> store.h store.cc
> 
> 引入bug 的是这两个文件

https://github.com/facebook/rocksdb/issues/11349

一个怀疑。

rocksdb 跑在子线程，线程退出的时候没有对 rocksdb 做 dump，pikiwidb 退出以后，rocksdb 的 database 被销毁了，但是数据没有 dump 完。所有报了这个错

**Comment by Tangruilin** [comment]
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/23651891/69f40052-3b24-41d5-833b-fe9d30880f38)
可以看到 redis 类的析构函数没有跑到

这个析构函数里面对 rocksdb 的实例进行了退出处理

**Comment by LuckyTom1024** [comment]
core dump了一下，发现在rocksdb::DBImpl::CancelAllBackgroundWork获取的锁已经被销毁了
![710b232512610cf573bfcd67d4ccf2f](https://github.com/OpenAtomFoundation/pikiwidb/assets/62509266/cdeb4aa9-847c-4da1-a22e-c22417910be4)
![792857b61e7a329254d39bb2eb0585e](https://github.com/OpenAtomFoundation/pikiwidb/assets/62509266/b63c45c0-bb51-45dc-a773-8afd38af279b)

**Comment by LuckyTom1024** [comment]
![1715846998156](https://github.com/OpenAtomFoundation/pikiwidb/assets/62509266/4aa187e0-7be5-4d1d-8f3e-1ebb4aecfd7a)
gdb打断点复现了一下，看上面的提示信息，似乎是在主线程函数退出的时候，调用了这个rocksdb::Timer::~Timer的销毁函数（里面触发了rocksdb::port::Mutex::~Mutex的调用）
但是有一点比较奇怪，就是这个销毁的函数先于Redis::~Redis函数调用，但在进入了Redis::~Redis之后，连续触发了两次获取锁都成功了，在接着的第三次获取锁失败了（锁被销毁了），这中间没有触发过锁销毁的操作
![70b182ceecc5fc7c36887878bfb3b9e](https://github.com/OpenAtomFoundation/pikiwidb/assets/62509266/71c0a060-fb1e-42d8-aebe-8487f72271db)

**Comment by LuckyTom1024** [comment]
单独把CancelAllBackgroundWork操作放在了close操作里面，PikiwiDB::Run()函数退出之前调用了一下，跑了一下可以正常退出了
![9c55f042d5516e69b719e88c932ab50](https://github.com/OpenAtomFoundation/pikiwidb/assets/62509266/d981cc99-d26a-4d42-8f49-d4d7508d226a)
![9f840c6250c23d17c291a8aafe0b828](https://github.com/OpenAtomFoundation/pikiwidb/assets/62509266/0acb2338-e57b-4a69-b72e-5533ea0552dc)
![6a6acad90ad2961f5a292b0ce9c245c](https://github.com/OpenAtomFoundation/pikiwidb/assets/62509266/4928ac9c-3502-4ca3-ace8-d97eb321430b)

**Comment by LuckyTom1024** [comment]
侯盛鑫：可能是这个issue描述的bug， https://github.com/facebook/rocksdb/issues/11440
