### ISSUE TITLE
STRING command develop

### ISSUE THREAD

**Issue by lqxhub** [OpenAtomFoundation/pikiwidb-raft#31]
string 相关的命令开发

现在已经写了 `SET` 和 `GET`的简单实现,
https://github.com/OpenAtomFoundation/pikiwidb/blob/e05878dfe99c232be3a6f40b6dc9ab73785c7db0/src/cmd_kv.h#L15

命令的具体实现逻辑可以参考 **pika**, pika 的string类型命令的文件在 `pika_kv.cc`中
https://github.com/OpenAtomFoundation/pika/blob/bdf90e81dce4cb49650f1a0d801e1c4e691d692f/src/pika_kv.cc#L6

**Comment by AlexStocks** [comment]
Task List:

PCY:

```C++
strlen
mset
msetnx
setnx
setex
```

Henry:

```C++
psetex
getset
mget
append
bitcount
```

CSX:

```C++
bitop
getbit
setbit
incr
decr
```

QX:

```C++
incrby
incrbyfloat
decrby
getrange
setrange
```

**Comment by jettcc** [comment]
@lqxhub i want to join you

**Comment by lqxhub** [comment]
> @lqxhub i want to join you

```
incrby
incrbyfloat
decrby
getrange
setrange
```

这几个命令先给你来做吧, 有问题随时沟通

**Comment by jettcc** [comment]
> 这几个命令先给你来做吧, 有问题随时沟通

ok 😄

**Comment by quzizii** [comment]
我想要参与命令开发，可以分几个吗

**Comment by hahahashen** [comment]
set命令的ex nx选项什么的是不是还没有实现呀
