### ISSUE TITLE
build error: uint64_t doesn't name a type

### ISSUE THREAD

**Issue by chienguo** [OpenAtomFoundation/pikiwidb-raft#323]
### Is this a regression?

Yes

### Description

when I run `./build.sh`, the following error came out
```
/home/chien/pikiwidb/src/pstd/pstd_hash.cc:84:18: error: ‘uint64_t’ does not name a type
   84 |   using uint64 = uint64_t;
      |                  ^~~~~~~~
/home/chien/pikiwidb/src/pstd/pstd_hash.cc:77:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   76 | #include <cstring>
  +++ |+#include <cstdint>
```
here is my machine setup,
os: arch linux x86-64
compiler: GCC 14.1.1

Is it necessary to add the suggested header? If it is needed, then why it is absent in our codebase?

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by luky116** [comment]
@AlexStocks

**Comment by luky116** [comment]
@dingxiaoshuai123 @kaiyan

**Comment by KKorpse** [comment]
我们暂时都没法复现，可以再看看本地环境的问题？
