### ISSUE TITLE
cmake build fail on Debian12

### ISSUE THREAD

**Issue by lqxhub** [OpenAtomFoundation/pikiwidb-raft#330]
在Debian12上, unstable分支, 编译错误, 提示找不到 `gflags`
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/22992275/ce6f357f-e7a1-4ccb-96b2-e39c9ce4b9ee)

**Comment by LuckyTom1024** [comment]
https://github.com/OpenAtomFoundation/pikiwidb/pull/335
