### ISSUE TITLE
build error: 编译PikiwiDB时遇到多个CMake配置错误

### ISSUE THREAD

**Issue by goTtheFuego** [OpenAtomFoundation/pikiwidb-raft#331]
### Is this a regression?

Yes

### Description

在 wsl-Ubuntu 22.04.3 尝试从源代码编译PikiwiDB时，我遇到了一系列关于数据类型和字段未定义的CMake错误。具体问题如下：

- SSIZE_T数据类型在EVENT__SIZEOF_SSIZE_T_UPPER.c文件中未定义，可能需要更明确地包含适当的头文件。
- 在src.c文件中，sin6_len和sin_len字段在sockaddr_in6和sockaddr_in结构体中不存在，提示结构体字段不存在的错误。
- 尝试访问sockaddr_storage中不存在的__ss_family字段，这个字段可能因平台差异在某些系统中不存在。
- 在检查getauxval函数存在性的代码中，引用了不存在的auvx.h头文件，这可能是个错误的引用。
- 
这些问题可能涉及到平台特定的实现差异，或者是CMake脚本中的一些错误。希望能得到一些帮助或指导来解决这些编译问题。

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

### Please provide the version you discovered this bug in (check about page for version information)

```true
OS: Ubuntu 22.04.3 LTS
```

**Comment by luky116** [comment]
@dingxiaoshuai123
