### ISSUE TITLE
debug 版本编译失败

### ISSUE THREAD

**Issue by chanfun-ren** [OpenAtomFoundation/pikiwidb-raft#339]
### Is this a regression?

Yes

### Description

- 问题：在编译 pikiwidb debug 版本时，**链接阶段**产生大量 `undefined reference to __asan__xxx` 错误，如下错误截图
- 环境：
   - WSL2 Ubuntu 22.04.4 LTS 
   - gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
   - cmake version 3.22.1
- 编译命令：`./build.sh --debug`

### Screenshots or videos

- 部分错误截图：
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/55045688/4b16e468-a846-403c-ac16-ce943da3cae6)

![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/55045688/4374a4a8-54fd-4f21-8ff5-b91d5f2abc8f)

### Anything else?

初步排查：
- 引发错误的代码（看起来像是没有设置 linker 的 ASAN 相关参数？）：
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/55045688/b434bb9a-e581-449a-92eb-fd4f06e37d8e)

**Comment by KKorpse** [comment]
@李风涛

**Comment by clearocean621** [comment]
> @李风涛
OK
