### ISSUE TITLE
HASHcommand develop

### ISSUE THREAD

**Issue by lqxhub** [OpenAtomFoundation/pikiwidb-raft#38]
### hash 类型相关的命令开发
hash 类型包含的命令
1. hdel
2. hexists
3. hset
4. hget
5. hmget
6. hmset
7. hgetall
8. hkeys
9. hlen
10. hstrlen
11. hrandfield
12. hscan
13. hsetnx
14. hincrby
15. hincrbyfloat
16. hvals

**Comment by lqxhub** [comment]
@quzizii 先开发这几个命令, hash类型的命令,需要新建一个文件,文件格式参考 `cmd_kv`, 有问题随机沟通

```
hdel
hexists
hset
hget
hmget
hmset
```

**Comment by lqxhub** [comment]
@longfar-ncy
```
hmget
hmset
hgetall
hkeys
```

**Comment by quzizii** [comment]
关于hset命令的实现问题：

https://github.com/OpenAtomFoundation/pikiwidb/issues/51

**Comment by AlexStocks** [comment]
ncy:
hlen
hstrlen
hrandfield
hscan

csx:
hsetnx
hincrby

pcy:
hincrbyfloat
hvals
