### ISSUE TITLE
Startup segment error

### ISSUE THREAD

**Issue by panlei-coder** [OpenAtomFoundation/pikiwidb-raft#389]
程序启动直接段错误了:
![1722125154456](https://github.com/user-attachments/assets/c9c730f0-a6b6-48ae-818f-99f53e597d16)
原因是下面 pikiwidb.cc 文件中这段代码：
![1722102790127](https://github.com/user-attachments/assets/8deed73a-fa81-4a3f-afa2-faa08c9c0fa3)

在 main 函数中把 InitLimit() 注释掉就没问题。

**Comment by AlexStocks** [comment]
那就看看 initLimit() 问题出在了哪里，别急着把这个功能干掉

**Comment by LuckyTom1024** [comment]
![6801a648c7b3fe62e7d25b463e90888](https://github.com/user-attachments/assets/76b8f147-3ea3-42b2-874d-de02578cf7f0)

**Comment by LuckyTom1024** [comment]
> 那就看看 initLimit() 问题出在了哪里，别急着把这个功能干掉

我后续找个时间定位一下这个问题

**Comment by AlexStocks** [comment]
![image](https://github.com/user-attachments/assets/4309b1e7-04e4-4e29-a3b2-00210ae8266c)

InitLimit 里面失败后输出了日志，而这时 log 对象还不存在。已经在 PR https://github.com/OpenAtomFoundation/pikiwidb/pull/381 中修复这个问题。
