### ISSUE TITLE
Please change README.md `sh ./etc/script/build.sh` to `./etc/script/build.sh`

### ISSUE THREAD

**Issue by Iam-WenYi** [OpenAtomFoundation/pikiwidb-raft#409]
### Is this a regression?

No

### Description

![image](https://github.com/user-attachments/assets/1051b38d-3ed0-4876-81e4-b6e9b208d802)
![image](https://github.com/user-attachments/assets/fd1e1629-609d-4351-8316-c320e5e7f08f)

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

### Please provide the version you discovered this bug in (check about page for version information)

```true
OS: Ubuntu
Pika: latest version (I git clone the master)
```

**Comment by AlexStocks** [comment]
ubuntu 上，sh 默认不是 bash，是 dash，需要你改成 bash

**Comment by AlexStocks** [comment]
QX: 去掉 sh 即可
