### ISSUE TITLE
ERR PRAFT is not initialized

### ISSUE THREAD

**Issue by Iam-WenYi** [OpenAtomFoundation/pikiwidb-raft#412]
### Is this a regression?

No

### Description

![图片](https://github.com/user-attachments/assets/b7063d85-c45c-49d2-bfba-6c31fdff7bde)
![图片](https://github.com/user-attachments/assets/4fbdd054-2627-496a-b303-6a7f930b91bc)

Redis 客户端连接不正确

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Ubuntu 24.0 LTS
PikiwiDB 4.0.0
```

**Comment by Iam-WenYi** [comment]
![图片](https://github.com/user-attachments/assets/a867ed98-f895-4f35-aa67-b6820277398e)

**Comment by Iam-WenYi** [comment]
![图片](https://github.com/user-attachments/assets/6f3e4e3d-de18-4cb9-a7aa-ca188ba1f4ce)

**Comment by Iam-WenYi** [comment]
我等会会去调整编译选项，然后测试

**Comment by Iam-WenYi** [comment]
配置为 no，初始化为 true

**Comment by AlexStocks** [comment]
编译完毕后，这样执行
bin/pikiwidb etc/conf/pikiwidb.conf

**Comment by Iam-WenYi** [comment]
![Uploading 图片.png…]()

问题解决，我会补充对应的文档过来

**Comment by Iam-WenYi** [comment]
![图片](https://github.com/user-attachments/assets/80845e19-94f3-4cd9-ab4e-b0c4fffca387)
