### ISSUE TITLE
Discuss problem about hset command

### ISSUE THREAD

**Issue by quzizii** [OpenAtomFoundation/pikiwidb-raft#51]
redis提供的hset命令在写一个key时，支持同时写入多个field-value。

而pika的hset命令目前不支持，只支持一次写入一个key-field-value。

pikiwidb应该实现怎样的hset命令？

![mmexport1700832995574.png](https://github.com/OpenAtomFoundation/pikiwidb/assets/96002356/3dbd184e-3d36-4165-8243-902cf2774a54)

**Comment by AlexStocks** [comment]
按照最新的 redis 协议来实现。

**Comment by AlexStocks** [comment]
@quzizii  和 ncy 一块商量 hmset/hset hmget/hget 重复的问题
