### ISSUE TITLE
feature: change constant name style

### ISSUE THREAD

**Issue by AlexStocks** [OpenAtomFoundation/pikiwidb-raft#76]
### Description

Which PikiwiDB functionalities are relevant/related to the feature request?
No response

Description
统一 define 宏、const 常量、enum 常量 的命名方式：kCmdOK

### Proposed solution

none

### Alternatives considered

none

**Comment by AlexStocks** [comment]
![image](https://github.com/OpenAtomFoundation/pikiwidb/assets/7959374/4426a3a4-bd11-4761-851c-a7270a794aac)

@liuhaoran

ref: 
https://github.com/facebook/rocksdb/blob/main/util/status.cc

https://github.com/facebook/rocksdb/blob/main/fuzz/db_fuzzer.cc

**Comment by whr1118** [comment]
ok
